function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -5; // o_head
	global.__objectDepths[1] = 0; // o_player
	global.__objectDepths[2] = -1000; // o_player_control
	global.__objectDepths[3] = 0; // o_spike
	global.__objectDepths[4] = 0; // o_ground
	global.__objectDepths[5] = 0; // o_ground_plate
	global.__objectDepths[6] = 0; // o_up_S_right
	global.__objectDepths[7] = 0; // o_up_S_left
	global.__objectDepths[8] = 0; // o_up_S2_right
	global.__objectDepths[9] = 0; // o_up_S2_left
	global.__objectDepths[10] = -100; // o_glass
	global.__objectDepths[11] = -100; // o_water
	global.__objectDepths[12] = -100; // o_lava
	global.__objectDepths[13] = 0; // o_enemy_minor
	global.__objectDepths[14] = 0; // o_enemy_medium
	global.__objectDepths[15] = 0; // o_enemy_major
	global.__objectDepths[16] = 0; // o_enemy_heavy
	global.__objectDepths[17] = 0; // o_enemy_bandit
	global.__objectDepths[18] = 0; // o_enemy_robot_stationary_gun
	global.__objectDepths[19] = 0; // o_enemy_robot_stationary_m_gun
	global.__objectDepths[20] = 0; // o_enemy_robot_air_small
	global.__objectDepths[21] = 0; // o_enemy_robot_air_small_gun
	global.__objectDepths[22] = 0; // o_enemy_robot_air_small_bomb
	global.__objectDepths[23] = 0; // o_enemy_robot_glider_small
	global.__objectDepths[24] = 0; // o_enemy_robot_glider_small_gun
	global.__objectDepths[25] = 0; // o_enemy_robot_glider_small_bomb
	global.__objectDepths[26] = -100; // o_hold_2
	global.__objectDepths[27] = -100; // o_hold_3
	global.__objectDepths[28] = -100; // o_hold_5
	global.__objectDepths[29] = -100; // o_hold_6
	global.__objectDepths[30] = -100; // o_hold_8
	global.__objectDepths[31] = -100; // o_hold_A_2
	global.__objectDepths[32] = -100; // o_hold_A_3
	global.__objectDepths[33] = -100; // o_hold_A_4
	global.__objectDepths[34] = -100; // o_hold_A_6
	global.__objectDepths[35] = -100; // o_hold_A_7
	global.__objectDepths[36] = -100; // o_hold_A_8
	global.__objectDepths[37] = -100; // o_hold_shield_1
	global.__objectDepths[38] = -100; // o_hold_shield_3
	global.__objectDepths[39] = -100; // o_hold_shield_A_1
	global.__objectDepths[40] = -100; // o_hold_shield_A_4
	global.__objectDepths[41] = -100; // o_hold_shield_A_8
	global.__objectDepths[42] = -100; // o_hold_jetpack_A_1
	global.__objectDepths[43] = -100; // o_hold_jetpack_A_3
	global.__objectDepths[44] = -100; // o_hold_jetpack_A_4
	global.__objectDepths[45] = -100; // o_hold_jetpack_A_7
	global.__objectDepths[46] = -100; // o_hold_jetpack_A_8
	global.__objectDepths[47] = -15; // o_gun_1
	global.__objectDepths[48] = -15; // o_gun_2
	global.__objectDepths[49] = -15; // o_gun_3
	global.__objectDepths[50] = -15; // o_gun_4
	global.__objectDepths[51] = -15; // o_gun_5
	global.__objectDepths[52] = -15; // o_gun_6
	global.__objectDepths[53] = -15; // o_gun_7
	global.__objectDepths[54] = -15; // o_gun_8
	global.__objectDepths[55] = -15; // o_gun_9
	global.__objectDepths[56] = -15; // o_gun_A_1
	global.__objectDepths[57] = -15; // o_gun_A_2
	global.__objectDepths[58] = -15; // o_gun_A_3
	global.__objectDepths[59] = -15; // o_gun_A_4
	global.__objectDepths[60] = -15; // o_gun_A_5
	global.__objectDepths[61] = -15; // o_gun_A_6
	global.__objectDepths[62] = -15; // o_gun_A_7
	global.__objectDepths[63] = -15; // o_gun_A_8
	global.__objectDepths[64] = 1; // o_crate_none
	global.__objectDepths[65] = 1; // o_crate
	global.__objectDepths[66] = 1; // o_crate_exp
	global.__objectDepths[67] = 1; // o_crate_weapon
	global.__objectDepths[68] = 1; // o_crate_power_up
	global.__objectDepths[69] = 1; // o_crate_health
	global.__objectDepths[70] = 1; // o_crate_s_none
	global.__objectDepths[71] = 1; // o_crate_s
	global.__objectDepths[72] = 1000000; // o_breakable_bricks_8x4
	global.__objectDepths[73] = 1000000; // o_breakable_bricks_2x6
	global.__objectDepths[74] = -4; // o_farmer
	global.__objectDepths[75] = -4; // o_civilian
	global.__objectDepths[76] = -4; // o_paramedic
	global.__objectDepths[77] = -4; // o_soldier
	global.__objectDepths[78] = 10000000; // o_bkg_world_1_control
	global.__objectDepths[79] = -100000; // o_bkg_lighting_night
	global.__objectDepths[80] = -100000; // o_bkg_rain
	global.__objectDepths[81] = 0; // o_world_gravity
	global.__objectDepths[82] = -6; // o_stud_silver
	global.__objectDepths[83] = -6; // o_stud_gold
	global.__objectDepths[84] = -6; // o_stud_blue
	global.__objectDepths[85] = -6; // o_stud_purple
	global.__objectDepths[86] = -6; // o_stud_pink
	global.__objectDepths[87] = -6; // o_stud_green
	global.__objectDepths[88] = 0; // o_walk_up
	global.__objectDepths[89] = 0; // o_jump_up
	global.__objectDepths[90] = 0; // o_damage_up
	global.__objectDepths[91] = 0; // o_damage_up_tier_2
	global.__objectDepths[92] = 0; // o_shield_up
	global.__objectDepths[93] = 0; // o_shield_up_tier_2
	global.__objectDepths[94] = 0; // o_key
	global.__objectDepths[95] = -6; // o_ammobox_s
	global.__objectDepths[96] = -6; // o_ammobox_m
	global.__objectDepths[97] = -6; // o_ammobox_l
	global.__objectDepths[98] = -6; // o_heart_s
	global.__objectDepths[99] = -6; // o_heart_m
	global.__objectDepths[100] = -6; // o_heart_l
	global.__objectDepths[101] = 0; // o_bullet_1
	global.__objectDepths[102] = 0; // o_bullet_2
	global.__objectDepths[103] = 0; // o_bullet_3
	global.__objectDepths[104] = 0; // o_bullet_4
	global.__objectDepths[105] = 0; // o_bullet_5
	global.__objectDepths[106] = 0; // o_bullet_6
	global.__objectDepths[107] = 0; // o_bullet_7
	global.__objectDepths[108] = 0; // o_bullet_8
	global.__objectDepths[109] = 0; // o_bullet_9
	global.__objectDepths[110] = 0; // o_bullet_A_1
	global.__objectDepths[111] = 0; // o_bullet_A_2
	global.__objectDepths[112] = 0; // o_bullet_A_3
	global.__objectDepths[113] = 0; // o_bullet_A_4
	global.__objectDepths[114] = 0; // o_bullet_A_5
	global.__objectDepths[115] = 0; // o_bullet_A_6
	global.__objectDepths[116] = 0; // o_bullet_A_7
	global.__objectDepths[117] = 0; // o_bullet_A_8
	global.__objectDepths[118] = 0; // o_laser_robot
	global.__objectDepths[119] = 0; // o_laser_robot_M
	global.__objectDepths[120] = 0; // o_robot_bomb
	global.__objectDepths[121] = 0; // o_trail_4
	global.__objectDepths[122] = 0; // o_trail_A_6
	global.__objectDepths[123] = 0; // o_trail_A_7
	global.__objectDepths[124] = 1000002; // o_bkg_ufo
	global.__objectDepths[125] = -2; // o_enemy_arm_A_1_minor
	global.__objectDepths[126] = -2; // o_enemy_arm_A_1_medium
	global.__objectDepths[127] = -2; // o_enemy_arm_A_1_major
	global.__objectDepths[128] = -2; // o_enemy_arm_A_2_minor
	global.__objectDepths[129] = -2; // o_enemy_arm_A_2_medium
	global.__objectDepths[130] = -2; // o_enemy_arm_A_2_major
	global.__objectDepths[131] = -2; // o_enemy_arm_A_2_heavy
	global.__objectDepths[132] = -2; // o_enemy_arm_A_3_medium
	global.__objectDepths[133] = -2; // o_enemy_arm_A_3_major
	global.__objectDepths[134] = -2; // o_enemy_arm_A_4_major
	global.__objectDepths[135] = -2; // o_enemy_arm_A_5_heavy
	global.__objectDepths[136] = -2; // o_enemy_arm_A_6_heavy
	global.__objectDepths[137] = -2; // o_enemy_arm_A_7_major
	global.__objectDepths[138] = -2; // o_enemy_arm_A_8_medium
	global.__objectDepths[139] = -2; // o_enemy_arm_A_8_major
	global.__objectDepths[140] = -2; // o_enemy_arm_1_bandit
	global.__objectDepths[141] = -2; // o_enemy_arm_2_bandit
	global.__objectDepths[142] = -2; // o_enemy_arm_3_bandit
	global.__objectDepths[143] = -2; // o_enemy_arm_5_bandit
	global.__objectDepths[144] = -2; // o_enemy_arm_6_bandit
	global.__objectDepths[145] = -2; // o_enemy_arm_8_bandit
	global.__objectDepths[146] = -1; // o_enemy_arm_shield_medium
	global.__objectDepths[147] = -1; // o_enemy_arm_shield_major
	global.__objectDepths[148] = -1; // o_enemy_arm_shield_bandit
	global.__objectDepths[149] = -3; // o_enemy_robot_stationary_head_gun
	global.__objectDepths[150] = -3; // o_enemy_robot_stationary_head_m_gun
	global.__objectDepths[151] = -3; // o_enemy_robot_air_small_gun_gun
	global.__objectDepths[152] = -1; // o_enemy_head
	global.__objectDepths[153] = -100; // o_exp
	global.__objectDepths[154] = -100; // o_exp_G_1_area
	global.__objectDepths[155] = -100; // o_exp_gun_6_area
	global.__objectDepths[156] = -100; // o_exp_robot_bomb_area
	global.__objectDepths[157] = -100; // o_exp_gun_8_area
	global.__objectDepths[158] = -100; // o_exp_gun_9_area
	global.__objectDepths[159] = -100; // o_exp_gun_A_5_area
	global.__objectDepths[160] = -100; // o_exp_crate_area
	global.__objectDepths[161] = -2; // o_grenadeT
	global.__objectDepths[162] = -16; // o_flash
	global.__objectDepths[163] = 0; // o_speech_bubble
	global.__objectDepths[164] = -10; // o_bit
	global.__objectDepths[165] = -10; // o_splinter
	global.__objectDepths[166] = -10; // o_splinter_light_grey
	global.__objectDepths[167] = 0; // o_propeller
	global.__objectDepths[168] = -100; // o_droplet
	global.__objectDepths[169] = -100; // o_drip
	global.__objectDepths[170] = 0; // o_blockP
	global.__objectDepths[171] = 0; // o_shieldP
	global.__objectDepths[172] = 0; // o_hazardP
	global.__objectDepths[173] = 0; // o_upP
	global.__objectDepths[174] = 0; // o_bulletP
	global.__objectDepths[175] = 0; // o_enemyP
	global.__objectDepths[176] = 0; // o_enemy_alienP
	global.__objectDepths[177] = 0; // o_enemy_banditP
	global.__objectDepths[178] = 0; // o_enemy_robotP
	global.__objectDepths[179] = 0; // o_hitP
	global.__objectDepths[180] = 0; // o_crateP
	global.__objectDepths[181] = 0; // o_deadly_expP
	global.__objectDepths[182] = 0; // o_breakable_bricksP
	global.__objectDepths[183] = 0; // o_hostageP
	global.__objectDepths[184] = 0; // o_gunP
	global.__objectDepths[185] = 0; // o_doorP
	global.__objectDepths[186] = 0; // o_conveyor_beltP
	global.__objectDepths[187] = 0; // o_interactP
	global.__objectDepths[188] = 0; // o_enemy_barrier
	global.__objectDepths[189] = 0; // o_barrier_edge
	global.__objectDepths[190] = -6; // o_grenadeG
	global.__objectDepths[191] = 0; // o_trampoline
	global.__objectDepths[192] = 0; // o_trampoline_air
	global.__objectDepths[193] = 0; // o_door_white
	global.__objectDepths[194] = 0; // o_door_lattice
	global.__objectDepths[195] = 0; // o_door_half_lattice
	global.__objectDepths[196] = 0; // o_conveyor_belt_s
	global.__objectDepths[197] = 0; // o_conveyor_belt_m
	global.__objectDepths[198] = 0; // o_conveyor_belt_l
	global.__objectDepths[199] = -100050; // o_light
	global.__objectDepths[200] = -100050; // o_light_fade
	global.__objectDepths[201] = -100; // o_left
	global.__objectDepths[202] = -100; // o_right
	global.__objectDepths[203] = -100; // o_up
	global.__objectDepths[204] = -100; // o_down
	global.__objectDepths[205] = -100; // o_stop
	global.__objectDepths[206] = 1000001; // o_lightpost
	global.__objectDepths[207] = 2; // o_light_wall
	global.__objectDepths[208] = 1000001; // o_cactus
	global.__objectDepths[209] = 1000001; // o_mailbox_blue
	global.__objectDepths[210] = 1000001; // o_mailbox_red
	global.__objectDepths[211] = 1000001; // o_trash_grey
	global.__objectDepths[212] = 1000001; // o_trash_green
	global.__objectDepths[213] = 2; // o_factory_part_1
	global.__objectDepths[214] = 2; // o_factory_part_2
	global.__objectDepths[215] = 0; // activation_redP
	global.__objectDepths[216] = 0; // o_door_red
	global.__objectDepths[217] = 0; // o_latch_red
	global.__objectDepths[218] = 0; // o_button_red
	global.__objectDepths[219] = 0; // o_button_press_red
	global.__objectDepths[220] = 0; // o_left_red
	global.__objectDepths[221] = 0; // o_right_red
	global.__objectDepths[222] = 0; // o_up_red
	global.__objectDepths[223] = 0; // o_down_red
	global.__objectDepths[224] = 0; // activation_blueP
	global.__objectDepths[225] = 0; // o_door_blue
	global.__objectDepths[226] = 0; // o_latch_blue
	global.__objectDepths[227] = 0; // o_button_blue
	global.__objectDepths[228] = 0; // o_button_press_blue
	global.__objectDepths[229] = 0; // o_left_blue
	global.__objectDepths[230] = 0; // o_right_blue
	global.__objectDepths[231] = 0; // o_up_blue
	global.__objectDepths[232] = 0; // o_down_blue
	global.__objectDepths[233] = 0; // activation_greenP
	global.__objectDepths[234] = 0; // o_door_green
	global.__objectDepths[235] = 0; // o_latch_green
	global.__objectDepths[236] = 0; // o_green_button
	global.__objectDepths[237] = 0; // o_button_press_green
	global.__objectDepths[238] = 0; // o_left_green
	global.__objectDepths[239] = 0; // o_right_green
	global.__objectDepths[240] = 0; // o_up_green
	global.__objectDepths[241] = 0; // o_down_green


	global.__objectNames[0] = "o_head";
	global.__objectNames[1] = "o_player";
	global.__objectNames[2] = "o_player_control";
	global.__objectNames[3] = "o_spike";
	global.__objectNames[4] = "o_ground";
	global.__objectNames[5] = "o_ground_plate";
	global.__objectNames[6] = "o_up_S_right";
	global.__objectNames[7] = "o_up_S_left";
	global.__objectNames[8] = "o_up_S2_right";
	global.__objectNames[9] = "o_up_S2_left";
	global.__objectNames[10] = "o_glass";
	global.__objectNames[11] = "o_water";
	global.__objectNames[12] = "o_lava";
	global.__objectNames[13] = "o_enemy_minor";
	global.__objectNames[14] = "o_enemy_medium";
	global.__objectNames[15] = "o_enemy_major";
	global.__objectNames[16] = "o_enemy_heavy";
	global.__objectNames[17] = "o_enemy_bandit";
	global.__objectNames[18] = "o_enemy_robot_stationary_gun";
	global.__objectNames[19] = "o_enemy_robot_stationary_m_gun";
	global.__objectNames[20] = "o_enemy_robot_air_small";
	global.__objectNames[21] = "o_enemy_robot_air_small_gun";
	global.__objectNames[22] = "o_enemy_robot_air_small_bomb";
	global.__objectNames[23] = "o_enemy_robot_glider_small";
	global.__objectNames[24] = "o_enemy_robot_glider_small_gun";
	global.__objectNames[25] = "o_enemy_robot_glider_small_bomb";
	global.__objectNames[26] = "o_hold_2";
	global.__objectNames[27] = "o_hold_3";
	global.__objectNames[28] = "o_hold_5";
	global.__objectNames[29] = "o_hold_6";
	global.__objectNames[30] = "o_hold_8";
	global.__objectNames[31] = "o_hold_A_2";
	global.__objectNames[32] = "o_hold_A_3";
	global.__objectNames[33] = "o_hold_A_4";
	global.__objectNames[34] = "o_hold_A_6";
	global.__objectNames[35] = "o_hold_A_7";
	global.__objectNames[36] = "o_hold_A_8";
	global.__objectNames[37] = "o_hold_shield_1";
	global.__objectNames[38] = "o_hold_shield_3";
	global.__objectNames[39] = "o_hold_shield_A_1";
	global.__objectNames[40] = "o_hold_shield_A_4";
	global.__objectNames[41] = "o_hold_shield_A_8";
	global.__objectNames[42] = "o_hold_jetpack_A_1";
	global.__objectNames[43] = "o_hold_jetpack_A_3";
	global.__objectNames[44] = "o_hold_jetpack_A_4";
	global.__objectNames[45] = "o_hold_jetpack_A_7";
	global.__objectNames[46] = "o_hold_jetpack_A_8";
	global.__objectNames[47] = "o_gun_1";
	global.__objectNames[48] = "o_gun_2";
	global.__objectNames[49] = "o_gun_3";
	global.__objectNames[50] = "o_gun_4";
	global.__objectNames[51] = "o_gun_5";
	global.__objectNames[52] = "o_gun_6";
	global.__objectNames[53] = "o_gun_7";
	global.__objectNames[54] = "o_gun_8";
	global.__objectNames[55] = "o_gun_9";
	global.__objectNames[56] = "o_gun_A_1";
	global.__objectNames[57] = "o_gun_A_2";
	global.__objectNames[58] = "o_gun_A_3";
	global.__objectNames[59] = "o_gun_A_4";
	global.__objectNames[60] = "o_gun_A_5";
	global.__objectNames[61] = "o_gun_A_6";
	global.__objectNames[62] = "o_gun_A_7";
	global.__objectNames[63] = "o_gun_A_8";
	global.__objectNames[64] = "o_crate_none";
	global.__objectNames[65] = "o_crate";
	global.__objectNames[66] = "o_crate_exp";
	global.__objectNames[67] = "o_crate_weapon";
	global.__objectNames[68] = "o_crate_power_up";
	global.__objectNames[69] = "o_crate_health";
	global.__objectNames[70] = "o_crate_s_none";
	global.__objectNames[71] = "o_crate_s";
	global.__objectNames[72] = "o_breakable_bricks_8x4";
	global.__objectNames[73] = "o_breakable_bricks_2x6";
	global.__objectNames[74] = "o_farmer";
	global.__objectNames[75] = "o_civilian";
	global.__objectNames[76] = "o_paramedic";
	global.__objectNames[77] = "o_soldier";
	global.__objectNames[78] = "o_bkg_world_1_control";
	global.__objectNames[79] = "o_bkg_lighting_night";
	global.__objectNames[80] = "o_bkg_rain";
	global.__objectNames[81] = "o_world_gravity";
	global.__objectNames[82] = "o_stud_silver";
	global.__objectNames[83] = "o_stud_gold";
	global.__objectNames[84] = "o_stud_blue";
	global.__objectNames[85] = "o_stud_purple";
	global.__objectNames[86] = "o_stud_pink";
	global.__objectNames[87] = "o_stud_green";
	global.__objectNames[88] = "o_walk_up";
	global.__objectNames[89] = "o_jump_up";
	global.__objectNames[90] = "o_damage_up";
	global.__objectNames[91] = "o_damage_up_tier_2";
	global.__objectNames[92] = "o_shield_up";
	global.__objectNames[93] = "o_shield_up_tier_2";
	global.__objectNames[94] = "o_key";
	global.__objectNames[95] = "o_ammobox_s";
	global.__objectNames[96] = "o_ammobox_m";
	global.__objectNames[97] = "o_ammobox_l";
	global.__objectNames[98] = "o_heart_s";
	global.__objectNames[99] = "o_heart_m";
	global.__objectNames[100] = "o_heart_l";
	global.__objectNames[101] = "o_bullet_1";
	global.__objectNames[102] = "o_bullet_2";
	global.__objectNames[103] = "o_bullet_3";
	global.__objectNames[104] = "o_bullet_4";
	global.__objectNames[105] = "o_bullet_5";
	global.__objectNames[106] = "o_bullet_6";
	global.__objectNames[107] = "o_bullet_7";
	global.__objectNames[108] = "o_bullet_8";
	global.__objectNames[109] = "o_bullet_9";
	global.__objectNames[110] = "o_bullet_A_1";
	global.__objectNames[111] = "o_bullet_A_2";
	global.__objectNames[112] = "o_bullet_A_3";
	global.__objectNames[113] = "o_bullet_A_4";
	global.__objectNames[114] = "o_bullet_A_5";
	global.__objectNames[115] = "o_bullet_A_6";
	global.__objectNames[116] = "o_bullet_A_7";
	global.__objectNames[117] = "o_bullet_A_8";
	global.__objectNames[118] = "o_laser_robot";
	global.__objectNames[119] = "o_laser_robot_M";
	global.__objectNames[120] = "o_robot_bomb";
	global.__objectNames[121] = "o_trail_4";
	global.__objectNames[122] = "o_trail_A_6";
	global.__objectNames[123] = "o_trail_A_7";
	global.__objectNames[124] = "o_bkg_ufo";
	global.__objectNames[125] = "o_enemy_arm_A_1_minor";
	global.__objectNames[126] = "o_enemy_arm_A_1_medium";
	global.__objectNames[127] = "o_enemy_arm_A_1_major";
	global.__objectNames[128] = "o_enemy_arm_A_2_minor";
	global.__objectNames[129] = "o_enemy_arm_A_2_medium";
	global.__objectNames[130] = "o_enemy_arm_A_2_major";
	global.__objectNames[131] = "o_enemy_arm_A_2_heavy";
	global.__objectNames[132] = "o_enemy_arm_A_3_medium";
	global.__objectNames[133] = "o_enemy_arm_A_3_major";
	global.__objectNames[134] = "o_enemy_arm_A_4_major";
	global.__objectNames[135] = "o_enemy_arm_A_5_heavy";
	global.__objectNames[136] = "o_enemy_arm_A_6_heavy";
	global.__objectNames[137] = "o_enemy_arm_A_7_major";
	global.__objectNames[138] = "o_enemy_arm_A_8_medium";
	global.__objectNames[139] = "o_enemy_arm_A_8_major";
	global.__objectNames[140] = "o_enemy_arm_1_bandit";
	global.__objectNames[141] = "o_enemy_arm_2_bandit";
	global.__objectNames[142] = "o_enemy_arm_3_bandit";
	global.__objectNames[143] = "o_enemy_arm_5_bandit";
	global.__objectNames[144] = "o_enemy_arm_6_bandit";
	global.__objectNames[145] = "o_enemy_arm_8_bandit";
	global.__objectNames[146] = "o_enemy_arm_shield_medium";
	global.__objectNames[147] = "o_enemy_arm_shield_major";
	global.__objectNames[148] = "o_enemy_arm_shield_bandit";
	global.__objectNames[149] = "o_enemy_robot_stationary_head_gun";
	global.__objectNames[150] = "o_enemy_robot_stationary_head_m_gun";
	global.__objectNames[151] = "o_enemy_robot_air_small_gun_gun";
	global.__objectNames[152] = "o_enemy_head";
	global.__objectNames[153] = "o_exp";
	global.__objectNames[154] = "o_exp_G_1_area";
	global.__objectNames[155] = "o_exp_gun_6_area";
	global.__objectNames[156] = "o_exp_robot_bomb_area";
	global.__objectNames[157] = "o_exp_gun_8_area";
	global.__objectNames[158] = "o_exp_gun_9_area";
	global.__objectNames[159] = "o_exp_gun_A_5_area";
	global.__objectNames[160] = "o_exp_crate_area";
	global.__objectNames[161] = "o_grenadeT";
	global.__objectNames[162] = "o_flash";
	global.__objectNames[163] = "o_speech_bubble";
	global.__objectNames[164] = "o_bit";
	global.__objectNames[165] = "o_splinter";
	global.__objectNames[166] = "o_splinter_light_grey";
	global.__objectNames[167] = "o_propeller";
	global.__objectNames[168] = "o_droplet";
	global.__objectNames[169] = "o_drip";
	global.__objectNames[170] = "o_blockP";
	global.__objectNames[171] = "o_shieldP";
	global.__objectNames[172] = "o_hazardP";
	global.__objectNames[173] = "o_upP";
	global.__objectNames[174] = "o_bulletP";
	global.__objectNames[175] = "o_enemyP";
	global.__objectNames[176] = "o_enemy_alienP";
	global.__objectNames[177] = "o_enemy_banditP";
	global.__objectNames[178] = "o_enemy_robotP";
	global.__objectNames[179] = "o_hitP";
	global.__objectNames[180] = "o_crateP";
	global.__objectNames[181] = "o_deadly_expP";
	global.__objectNames[182] = "o_breakable_bricksP";
	global.__objectNames[183] = "o_hostageP";
	global.__objectNames[184] = "o_gunP";
	global.__objectNames[185] = "o_doorP";
	global.__objectNames[186] = "o_conveyor_beltP";
	global.__objectNames[187] = "o_interactP";
	global.__objectNames[188] = "o_enemy_barrier";
	global.__objectNames[189] = "o_barrier_edge";
	global.__objectNames[190] = "o_grenadeG";
	global.__objectNames[191] = "o_trampoline";
	global.__objectNames[192] = "o_trampoline_air";
	global.__objectNames[193] = "o_door_white";
	global.__objectNames[194] = "o_door_lattice";
	global.__objectNames[195] = "o_door_half_lattice";
	global.__objectNames[196] = "o_conveyor_belt_s";
	global.__objectNames[197] = "o_conveyor_belt_m";
	global.__objectNames[198] = "o_conveyor_belt_l";
	global.__objectNames[199] = "o_light";
	global.__objectNames[200] = "o_light_fade";
	global.__objectNames[201] = "o_left";
	global.__objectNames[202] = "o_right";
	global.__objectNames[203] = "o_up";
	global.__objectNames[204] = "o_down";
	global.__objectNames[205] = "o_stop";
	global.__objectNames[206] = "o_lightpost";
	global.__objectNames[207] = "o_light_wall";
	global.__objectNames[208] = "o_cactus";
	global.__objectNames[209] = "o_mailbox_blue";
	global.__objectNames[210] = "o_mailbox_red";
	global.__objectNames[211] = "o_trash_grey";
	global.__objectNames[212] = "o_trash_green";
	global.__objectNames[213] = "o_factory_part_1";
	global.__objectNames[214] = "o_factory_part_2";
	global.__objectNames[215] = "activation_redP";
	global.__objectNames[216] = "o_door_red";
	global.__objectNames[217] = "o_latch_red";
	global.__objectNames[218] = "o_button_red";
	global.__objectNames[219] = "o_button_press_red";
	global.__objectNames[220] = "o_left_red";
	global.__objectNames[221] = "o_right_red";
	global.__objectNames[222] = "o_up_red";
	global.__objectNames[223] = "o_down_red";
	global.__objectNames[224] = "activation_blueP";
	global.__objectNames[225] = "o_door_blue";
	global.__objectNames[226] = "o_latch_blue";
	global.__objectNames[227] = "o_button_blue";
	global.__objectNames[228] = "o_button_press_blue";
	global.__objectNames[229] = "o_left_blue";
	global.__objectNames[230] = "o_right_blue";
	global.__objectNames[231] = "o_up_blue";
	global.__objectNames[232] = "o_down_blue";
	global.__objectNames[233] = "activation_greenP";
	global.__objectNames[234] = "o_door_green";
	global.__objectNames[235] = "o_latch_green";
	global.__objectNames[236] = "o_green_button";
	global.__objectNames[237] = "o_button_press_green";
	global.__objectNames[238] = "o_left_green";
	global.__objectNames[239] = "o_right_green";
	global.__objectNames[240] = "o_up_green";
	global.__objectNames[241] = "o_down_green";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
